name: Deploy Static Website to S3

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} --exclude ".git/*" --delete

      - name: Configure S3 bucket for static website hosting
        run: |
          aws s3 website s3://${{ secrets.S3_BUCKET }}/ \
            --index-document index.html \
            --error-document error.html || echo "Bucket already configured"
            - name: Output website URL
  
